### ISSUE TITLE
Each application report page points to invalid ARCHEO report and ARCHEO log files.

### ISSUE THREAD

**Issue by nevenc** [vmware-tanzu/application-portfolio-auditor#15]
Each application page points to invalid ARCHEO report and ARCHEO log files, for example

`REPORT_ROOT/16__ARCHEO/myapp.war.html` points to
- `REPORT_ROOT/16__ARCHEO/16__ARCHEO` and 
- `REPORT_ROOT/16__ARCHEO/16__ARCHEO.log`

And it should point to:
- `REPORT_ROOT/16__ARCHEO` and 
- `REPORT_ROOT/16__ARCHEO.log`

**Comment by Maarc** [comment]
Closed by #16 

Thank you Neven!
