### ISSUE TITLE
date command used in 98__generate_timline.sh seems not to be compatible with Centos or Redhat

### ISSUE THREAD

**Issue by cpduemke** [vmware-tanzu/application-portfolio-auditor#25]
Hello,

I have updated the auditor to the current version 2.2.3 and every run stops with the following error:
> [2024_05_07__13_23_32] 98__generate_timeline.sh
> date: invalid option -- 'j'
> Try 'date --help' for more information.
> [cpduemke@acentos03 application-portfolio-auditor]$

date -j -f is used in the script, but the -j parameter only exists in BSD Unix variants and not in Linux, at least as far as I looked into it.

I build the auditor on a Centos 9 VM and tried to run it on a Redhat 8 VM. In both date has no -j parameter and -f also seems to have also a different meaning.

Would it be possible to use the 98 script from an older release as a workaround?

Regards 
Claus-Peter Dümke

**Comment by Maarc** [comment]
Hello Claus-Peter,

Thank you very much for filing this issue. Coincidentally, I stumbled upon it today and fixed it (f3128404de9f9ddc290c21dcf4336f7d3be3f0e8).

Please just check out the latest release and it should be fine.

Feel free to reopen the issue if you have any trouble related to this.

Best regards,

Marc
