### ISSUE TITLE
Application portfolio management

### ISSUE THREAD

**Issue by visi0n0wl** [vmware-tanzu/application-portfolio-auditor#4]
i do follow the steps in the below article to get it worked. but im facing issue while running the audit setup command. its stating that the docker images having issues to fetch up. help me out on this.
![Screenshot 2023-11-03 195727](https://github.com/vmware-tanzu/application-portfolio-auditor/assets/149783611/6f4c0240-0d0a-4049-9fed-e7a4276b1fa0)

**Comment by Maarc** [comment]
Hi @visi0n0wl

Thank you very much for sharing this issue. I crafted a small fix for it and will merge the PR on the main branch.
