### ISSUE TITLE
--archeo seems to break  k8 folder generation in 2.1.0

### ISSUE THREAD

**Issue by cpduemke** [vmware-tanzu/application-portfolio-auditor#7]
Hello,

we updated to Release 2.1.0 and --archeo seems to break the Kubernetes output.

if we use ./audit -a -g test -k  no _K8 folder is generated.

> >>>>>>> [2024_02_26__15_46_02] 97__generate_reports.sh
>     [SUCCESS] Open this file for reviewing all generated reports: /home/cpduemke/application-portfolio-auditor/reports/2024_02_26__15_37_36__test/index.html
>     [INFO] Open this file for reviewing all generated reports: /home/cpduemke/application-portfolio-auditor/reports/2024_02_26__15_37_36__test/cloud.html
>     [INFO] Open this file for reviewing all generated reports: /home/cpduemke/application-portfolio-auditor/reports/2024_02_26__15_37_36__test/security.html
> 97__generate_reports.sh: line 833: /home/cpduemke/application-portfolio-auditor/reports/2024_02_26__15_37_36__test/16__ARCHEO/simple-ear-1.10.9.ear.html: No such file or directory
> [cpduemke@acentos03 application-portfolio-auditor]$

if we run 2.1.0 with ./audit run -cwxlspm -g test -k the K8 folder is created again.

>>>>>>> [2024_02_26__16_03_24] 99__package_reports.sh
    [INFO] Packaging the reports - CF: false - K8: true - ZIP: false
    [SUCCESS] K8 deployment succesfully created. Deploy by executing: 'cd /home/cpduemke/application-portfolio-auditor/reports/2024_02_26__16_01_18__test_CF; ./deploy-docker.sh; # ... OR...; ./deploy-k8.sh'
<<<<<<< [2024_02_26__16_03_27] 99__package_reports.sh

[cpduemke@acentos03 application-portfolio-auditor]$

Regards 
cpduemke

**Comment by Maarc** [comment]
Hi cpduemke,

Thank you very much for sharing this bug. Unfortunately, I did not manage to reproduce your issue. However, it looks like there was a usage mix between "16__ARCHEO" and "16__Archeo" folders that I just fixed (a1f3e54039e7ac888cb036a986e9ff5f0a3cd450).

Could you please check out the latest version, run `./audit update` and try again?

If it does not work, I would be interested to known more about your test application(s), OS and hardware architecture to create a reproducer.

Best regards,

Marc

**Comment by cpduemke** [comment]
Hello Marc,

I synced with GitHub and ran ./audit update and afterwards if I run ./audit -a -g test -k the scan runs without error and generates a K8 Folder to build a container from.

The Test Application I used is the simple-ear mentioned in step 4 of the README. To run the application-portfolio-auditor I use a Vmware Fusion VM running Centos Stream 9 with the latest patches.

Thank you
cpduemke

**Comment by Maarc** [comment]
Great news! Thanks for the details. Feel free to reach out if you have any question.
